# Generated by Django 6.0.6 on 2026-06-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossover',
            name='position',
            field=models.CharField(default='after', max_length=10),
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('near_station', models.IntegerField()),
                ('track', models.CharField(default='up', max_length=10)),
                ('position', models.CharField(default='after', max_length=10)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.layout')),
            ],
        ),
    ]
