# Generated by Django 6.0.6 on 2026-06-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_crossover_position_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='layout_data',
            field=models.TextField(default='{}'),
        ),
    ]
